$(document).ready(function () {

$('#summon_cats').click(function(){
  $.ajax({
    url: "http://bitkittens.herokuapp.com/cats.json",
    method: 'GET',
    data: {}, // this is info were sending to the server. in this case - its meaningless.
    dataType: 'json'
  }).done(function (catlist) {
    var cats = catlist['cats']
  var first_cat = cats[0].photo;
 $('#cat1').css("background-image", 'url(' + first_cat + ')');
 $('#cat2').css("background-image", 'url(' + cats[1].photo + ')');
 $('#cat3').css("background-image", 'url(' + cats[2].photo + ')');
 $( "#test" ).append( "<div> all the cats have appeared. This text was generated inside of a div, which was also generated by javascript. </div>" );

    console.log(' loaded successfully');

  }).fail(function () {
    console.log('failed to load');
  })
});

});
